/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI_Dictionary;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
    import java.io.IOException;
    import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.speech.Central;
import javax.speech.EngineException;
import javax.speech.synthesis.Synthesizer;
import javax.speech.synthesis.SynthesizerModeDesc;


/**
 *
 * @author Tran Hong Quan
 */
public class DictionaryFrame extends javax.swing.JFrame {

    private Dictionary dictionary;
    private List<javax.swing.JButton> menuButtons = new ArrayList<>();
    private SimpleDictionary.DictionaryManagement simpleDictionary;

    private Synthesizer synthesizer;
    /**
     * Creates new form DictionaryFrame
     */
    public DictionaryFrame() {
        initSynthesizer();
        initComponents();
        dictionary = Dictionary.instance;
        initMenuButton();
        chooseSearchEnglishActionPerformed(null);
        simpleDictionary = new SimpleDictionary.DictionaryManagement();
        simpleDictionary.insertFromFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initSynthesizer(){
        System.setProperty("freetts.voices", "com.sun.speech.freetts.en.us.cmu_us_kal.KevinVoiceDirectory");
        try {
            Central.registerEngineCentral("com.sun.speech.freetts.jsapi.FreeTTSEngineCentral");
        } catch (EngineException e) {
            e.printStackTrace();
            return;
        }
        try {
            synthesizer = Central.createSynthesizer(new SynthesizerModeDesc(Locale.US));
            synthesizer.allocate();
            synthesizer.resume();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        nameApp = new javax.swing.JLabel();
        nameApp1 = new javax.swing.JLabel();
        chooseSearchEnglish = new javax.swing.JButton();
        chooseSearchVietnamese = new javax.swing.JButton();
        chooseSearchOnline = new javax.swing.JButton();
        chooseYourWords = new javax.swing.JButton();
        chooseGame = new javax.swing.JButton();
        tabs = new javax.swing.JTabbedPane();
        findEnglishWordTab = new javax.swing.JPanel();
        inputEngWord = new javax.swing.JTextField();
        FindEng = new javax.swing.JButton();
        showAllEngSearch = new javax.swing.JScrollPane();
        searchEngList = new javax.swing.JList<>();
        findVietnameseWordTab = new javax.swing.JPanel();
        inputViewWord = new javax.swing.JTextField();
        FindViet = new javax.swing.JButton();
        showAllViewSearch = new javax.swing.JScrollPane();
        searchVietList = new javax.swing.JList<>();
        onlineSearchTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputOnlineSearchTextArea = new javax.swing.JTextArea();
        VietEngOnlineButton = new javax.swing.JButton();
        EngVietOnlineButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputOnlineSearchTextArea = new javax.swing.JTextArea();
        wordTab = new javax.swing.JPanel();
        scrollPaneExplain = new javax.swing.JScrollPane();
        wordExplain = new javax.swing.JEditorPane();
        wordLabel = new javax.swing.JLabel();
        pronounce = new javax.swing.JLabel();
        soundButton = new javax.swing.JButton();
        YourWordTab = new javax.swing.JPanel();
        inputYourEngWord = new javax.swing.JTextField();
        showAllEngSearch1 = new javax.swing.JScrollPane();
        searchYourEngList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showYourVietWordField = new javax.swing.JTextField();
        showYourEngWordField = new javax.swing.JTextField();
        saveChangeYourWordButton = new javax.swing.JButton();
        deleteYourWordButton = new javax.swing.JButton();
        saveToFileYourWordButton = new javax.swing.JButton();
        readYourWordFromFile = new javax.swing.JButton();
        saveChangeYourWordButton1 = new javax.swing.JButton();
        addYourEngWordField = new javax.swing.JTextField();
        addYourVietWordField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(763, 570));
        setMinimumSize(new java.awt.Dimension(763, 570));
        setPreferredSize(new java.awt.Dimension(763, 570));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(0, 153, 204));
        menu.setFocusable(false);

        nameApp.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nameApp.setForeground(new java.awt.Color(255, 255, 255));
        nameApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameApp.setText("Từ Điển Anh Việt");

        nameApp1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nameApp1.setForeground(new java.awt.Color(255, 255, 255));
        nameApp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameApp1.setText("English Vietnamese Dictionary");

        chooseSearchEnglish.setBackground(new java.awt.Color(0, 123, 170));
        chooseSearchEnglish.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chooseSearchEnglish.setForeground(new java.awt.Color(255, 255, 255));
        chooseSearchEnglish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/engFind.png"))); // NOI18N
        chooseSearchEnglish.setText("Tra tiếng Anh");
        chooseSearchEnglish.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chooseSearchEnglish.setBorderPainted(false);
        chooseSearchEnglish.setContentAreaFilled(false);
        chooseSearchEnglish.setDefaultCapable(false);
        chooseSearchEnglish.setFocusPainted(false);
        chooseSearchEnglish.setFocusable(false);
        chooseSearchEnglish.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chooseSearchEnglish.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chooseSearchEnglish.setIconTextGap(10);
        chooseSearchEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseSearchEnglishActionPerformed(evt);
            }
        });

        chooseSearchVietnamese.setBackground(new java.awt.Color(0, 123, 170));
        chooseSearchVietnamese.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chooseSearchVietnamese.setForeground(new java.awt.Color(255, 255, 255));
        chooseSearchVietnamese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/vietFind.png"))); // NOI18N
        chooseSearchVietnamese.setText("Tra tiếng Việt");
        chooseSearchVietnamese.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chooseSearchVietnamese.setBorderPainted(false);
        chooseSearchVietnamese.setContentAreaFilled(false);
        chooseSearchVietnamese.setFocusable(false);
        chooseSearchVietnamese.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chooseSearchVietnamese.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chooseSearchVietnamese.setIconTextGap(10);
        chooseSearchVietnamese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseSearchVietnameseActionPerformed(evt);
            }
        });

        chooseSearchOnline.setBackground(new java.awt.Color(0, 123, 170));
        chooseSearchOnline.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chooseSearchOnline.setForeground(new java.awt.Color(255, 255, 255));
        chooseSearchOnline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ggdich.png"))); // NOI18N
        chooseSearchOnline.setText("Dịch Online");
        chooseSearchOnline.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chooseSearchOnline.setBorderPainted(false);
        chooseSearchOnline.setContentAreaFilled(false);
        chooseSearchOnline.setFocusable(false);
        chooseSearchOnline.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chooseSearchOnline.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chooseSearchOnline.setIconTextGap(10);
        chooseSearchOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseSearchOnlineActionPerformed(evt);
            }
        });

        chooseYourWords.setBackground(new java.awt.Color(0, 123, 170));
        chooseYourWords.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chooseYourWords.setForeground(new java.awt.Color(255, 255, 255));
        chooseYourWords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/chest.png"))); // NOI18N
        chooseYourWords.setText("Từ của bạn");
        chooseYourWords.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chooseYourWords.setBorderPainted(false);
        chooseYourWords.setContentAreaFilled(false);
        chooseYourWords.setFocusable(false);
        chooseYourWords.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chooseYourWords.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chooseYourWords.setIconTextGap(10);
        chooseYourWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseYourWordsActionPerformed(evt);
            }
        });

        chooseGame.setBackground(new java.awt.Color(0, 123, 170));
        chooseGame.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chooseGame.setForeground(new java.awt.Color(255, 255, 255));
        chooseGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/controller-game-icon.png"))); // NOI18N
        chooseGame.setText("Trò chơi");
        chooseGame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chooseGame.setBorderPainted(false);
        chooseGame.setContentAreaFilled(false);
        chooseGame.setFocusable(false);
        chooseGame.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chooseGame.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chooseGame.setIconTextGap(10);
        chooseGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chooseSearchEnglish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chooseSearchOnline, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameApp1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(chooseSearchVietnamese, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chooseYourWords, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chooseGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(nameApp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameApp1)
                .addGap(38, 38, 38)
                .addComponent(chooseSearchEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chooseSearchVietnamese, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chooseSearchOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chooseYourWords, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chooseGame, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 230, 630));

        findEnglishWordTab.setBackground(new java.awt.Color(230, 230, 230));

        inputEngWord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputEngWord.setForeground(new java.awt.Color(0, 0, 0));
        inputEngWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEngWordActionPerformed(evt);
            }
        });
        inputEngWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputEngWordKeyReleased(evt);
            }
        });

        FindEng.setBackground(new java.awt.Color(0, 153, 204));
        FindEng.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FindEng.setForeground(new java.awt.Color(255, 255, 255));
        FindEng.setText("Find");
        FindEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindEngActionPerformed(evt);
            }
        });

        searchEngList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchEngList.setForeground(new java.awt.Color(0, 0, 0));
        searchEngList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        searchEngList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchEngListMouseReleased(evt);
            }
        });
        searchEngList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchEngListKeyReleased(evt);
            }
        });
        showAllEngSearch.setViewportView(searchEngList);

        javax.swing.GroupLayout findEnglishWordTabLayout = new javax.swing.GroupLayout(findEnglishWordTab);
        findEnglishWordTab.setLayout(findEnglishWordTabLayout);
        findEnglishWordTabLayout.setHorizontalGroup(
            findEnglishWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findEnglishWordTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findEnglishWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(showAllEngSearch)
                    .addGroup(findEnglishWordTabLayout.createSequentialGroup()
                        .addComponent(inputEngWord, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FindEng, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        findEnglishWordTabLayout.setVerticalGroup(
            findEnglishWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findEnglishWordTabLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(findEnglishWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEngWord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindEng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(showAllEngSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabs.addTab("tab1", findEnglishWordTab);

        findVietnameseWordTab.setBackground(new java.awt.Color(230, 230, 230));

        inputViewWord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputViewWord.setForeground(new java.awt.Color(0, 0, 0));
        inputViewWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputViewWordActionPerformed(evt);
            }
        });
        inputViewWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputViewWordKeyReleased(evt);
            }
        });

        FindViet.setBackground(new java.awt.Color(0, 153, 204));
        FindViet.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FindViet.setForeground(new java.awt.Color(255, 255, 255));
        FindViet.setText("Find");
        FindViet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindVietActionPerformed(evt);
            }
        });

        searchVietList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchVietList.setForeground(new java.awt.Color(0, 0, 0));
        searchVietList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        searchVietList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchVietListMouseReleased(evt);
            }
        });
        searchVietList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchVietListKeyReleased(evt);
            }
        });
        showAllViewSearch.setViewportView(searchVietList);

        javax.swing.GroupLayout findVietnameseWordTabLayout = new javax.swing.GroupLayout(findVietnameseWordTab);
        findVietnameseWordTab.setLayout(findVietnameseWordTabLayout);
        findVietnameseWordTabLayout.setHorizontalGroup(
            findVietnameseWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findVietnameseWordTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findVietnameseWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(showAllViewSearch)
                    .addGroup(findVietnameseWordTabLayout.createSequentialGroup()
                        .addComponent(inputViewWord, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FindViet, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        findVietnameseWordTabLayout.setVerticalGroup(
            findVietnameseWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findVietnameseWordTabLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(findVietnameseWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputViewWord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindViet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(showAllViewSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabs.addTab("tab1", findVietnameseWordTab);

        onlineSearchTab.setBackground(new java.awt.Color(230, 230, 230));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        inputOnlineSearchTextArea.setColumns(20);
        inputOnlineSearchTextArea.setRows(5);
        inputOnlineSearchTextArea.setBorder(null);
        jScrollPane2.setViewportView(inputOnlineSearchTextArea);

        VietEngOnlineButton.setBackground(new java.awt.Color(0, 153, 204));
        VietEngOnlineButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        VietEngOnlineButton.setForeground(new java.awt.Color(255, 255, 255));
        VietEngOnlineButton.setText("Anh - Việt");
        VietEngOnlineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VietEngOnlineButtonActionPerformed(evt);
            }
        });

        EngVietOnlineButton.setBackground(new java.awt.Color(0, 153, 204));
        EngVietOnlineButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EngVietOnlineButton.setForeground(new java.awt.Color(255, 255, 255));
        EngVietOnlineButton.setText("Việt - Anh");
        EngVietOnlineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngVietOnlineButtonActionPerformed(evt);
            }
        });

        outputOnlineSearchTextArea.setEditable(false);
        outputOnlineSearchTextArea.setColumns(20);
        outputOnlineSearchTextArea.setRows(5);
        jScrollPane1.setViewportView(outputOnlineSearchTextArea);

        javax.swing.GroupLayout onlineSearchTabLayout = new javax.swing.GroupLayout(onlineSearchTab);
        onlineSearchTab.setLayout(onlineSearchTabLayout);
        onlineSearchTabLayout.setHorizontalGroup(
            onlineSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onlineSearchTabLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(VietEngOnlineButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(EngVietOnlineButton)
                .addGap(89, 89, 89))
            .addGroup(onlineSearchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(onlineSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        onlineSearchTabLayout.setVerticalGroup(
            onlineSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onlineSearchTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(onlineSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VietEngOnlineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EngVietOnlineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tabs.addTab("tab1", onlineSearchTab);

        wordTab.setBackground(new java.awt.Color(230, 230, 230));

        wordExplain.setEditable(false);
        wordExplain.setContentType("text/html"); // NOI18N
        wordExplain.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        wordExplain.setText("Hãy tìm kiếm từ bạn muốn");
        scrollPaneExplain.setViewportView(wordExplain);

        wordLabel.setBackground(new java.awt.Color(255, 255, 255));
        wordLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        wordLabel.setForeground(new java.awt.Color(0, 0, 0));
        wordLabel.setText("Nothing");
        wordLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        wordLabel.setOpaque(true);
        wordLabel.setVerifyInputWhenFocusTarget(false);

        pronounce.setBackground(new java.awt.Color(255, 255, 255));
        pronounce.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pronounce.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pronounce.setText("Nothing");
        pronounce.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pronounce.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pronounce.setOpaque(true);
        pronounce.setVerifyInputWhenFocusTarget(false);

        soundButton.setBackground(new java.awt.Color(0, 153, 204));
        soundButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Speaker_Icon.png"))); // NOI18N
        soundButton.setFocusable(false);
        soundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wordTabLayout = new javax.swing.GroupLayout(wordTab);
        wordTab.setLayout(wordTabLayout);
        wordTabLayout.setHorizontalGroup(
            wordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wordTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wordTabLayout.createSequentialGroup()
                        .addComponent(wordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(pronounce)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(soundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPaneExplain))
                .addContainerGap())
        );
        wordTabLayout.setVerticalGroup(
            wordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wordTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wordLabel)
                        .addComponent(pronounce))
                    .addComponent(soundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneExplain, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tabs.addTab("tab1", wordTab);

        YourWordTab.setBackground(new java.awt.Color(230, 230, 230));

        inputYourEngWord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputYourEngWord.setForeground(new java.awt.Color(0, 0, 0));
        inputYourEngWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputYourEngWordActionPerformed(evt);
            }
        });
        inputYourEngWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputYourEngWordKeyReleased(evt);
            }
        });

        searchYourEngList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchYourEngList.setForeground(new java.awt.Color(0, 0, 0));
        searchYourEngList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        searchYourEngList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchYourEngListMouseReleased(evt);
            }
        });
        searchYourEngList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchYourEngListKeyReleased(evt);
            }
        });
        showAllEngSearch1.setViewportView(searchYourEngList);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Tiếng Anh");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Tiếng Việt");

        showYourVietWordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showYourVietWordField.setForeground(new java.awt.Color(0, 0, 0));
        showYourVietWordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showYourVietWordFieldActionPerformed(evt);
            }
        });
        showYourVietWordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                showYourVietWordFieldKeyReleased(evt);
            }
        });

        showYourEngWordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showYourEngWordField.setForeground(new java.awt.Color(0, 0, 0));
        showYourEngWordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showYourEngWordFieldActionPerformed(evt);
            }
        });
        showYourEngWordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                showYourEngWordFieldKeyReleased(evt);
            }
        });

        saveChangeYourWordButton.setBackground(new java.awt.Color(0, 153, 204));
        saveChangeYourWordButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        saveChangeYourWordButton.setForeground(new java.awt.Color(255, 255, 255));
        saveChangeYourWordButton.setText("LƯU CHỈNH SỬA");
        saveChangeYourWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangeYourWordButtonActionPerformed(evt);
            }
        });

        deleteYourWordButton.setBackground(new java.awt.Color(0, 153, 204));
        deleteYourWordButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        deleteYourWordButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteYourWordButton.setText("XÓA TỪ");
        deleteYourWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteYourWordButtonActionPerformed(evt);
            }
        });

        saveToFileYourWordButton.setBackground(new java.awt.Color(0, 153, 204));
        saveToFileYourWordButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        saveToFileYourWordButton.setForeground(new java.awt.Color(255, 255, 255));
        saveToFileYourWordButton.setText("LƯU VÀO FILE");
        saveToFileYourWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToFileYourWordButtonActionPerformed(evt);
            }
        });

        readYourWordFromFile.setBackground(new java.awt.Color(0, 153, 204));
        readYourWordFromFile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        readYourWordFromFile.setForeground(new java.awt.Color(255, 255, 255));
        readYourWordFromFile.setText("XUẤT VÀO FILE");
        readYourWordFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readYourWordFromFileActionPerformed(evt);
            }
        });

        saveChangeYourWordButton1.setBackground(new java.awt.Color(0, 153, 204));
        saveChangeYourWordButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        saveChangeYourWordButton1.setForeground(new java.awt.Color(255, 255, 255));
        saveChangeYourWordButton1.setText("THÊM TỪ");
        saveChangeYourWordButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangeYourWordButton1ActionPerformed(evt);
            }
        });

        addYourEngWordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addYourEngWordField.setForeground(new java.awt.Color(0, 0, 0));
        addYourEngWordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addYourEngWordFieldActionPerformed(evt);
            }
        });
        addYourEngWordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addYourEngWordFieldKeyReleased(evt);
            }
        });

        addYourVietWordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addYourVietWordField.setForeground(new java.awt.Color(0, 0, 0));
        addYourVietWordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addYourVietWordFieldActionPerformed(evt);
            }
        });
        addYourVietWordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addYourVietWordFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout YourWordTabLayout = new javax.swing.GroupLayout(YourWordTab);
        YourWordTab.setLayout(YourWordTabLayout);
        YourWordTabLayout.setHorizontalGroup(
            YourWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, YourWordTabLayout.createSequentialGroup()
                .addGroup(YourWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, YourWordTabLayout.createSequentialGroup()
                        .addGroup(YourWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(YourWordTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(showAllEngSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(YourWordTabLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(89, 89, 89)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(YourWordTabLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveChangeYourWordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(YourWordTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(YourWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputYourEngWord)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, YourWordTabLayout.createSequentialGroup()
                                .addComponent(showYourEngWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(showYourVietWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, YourWordTabLayout.createSequentialGroup()
                                .addComponent(saveChangeYourWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteYourWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, YourWordTabLayout.createSequentialGroup()
                                .addComponent(saveToFileYourWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(readYourWordFromFile, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, YourWordTabLayout.createSequentialGroup()
                                .addComponent(addYourEngWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addYourVietWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        YourWordTabLayout.setVerticalGroup(
            YourWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YourWordTabLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(inputYourEngWord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showAllEngSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(YourWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(YourWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showYourVietWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showYourEngWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(YourWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveChangeYourWordButton)
                    .addComponent(deleteYourWordButton))
                .addGap(18, 18, 18)
                .addGroup(YourWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveToFileYourWordButton)
                    .addComponent(readYourWordFromFile))
                .addGap(38, 38, 38)
                .addGroup(YourWordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addYourVietWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addYourEngWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveChangeYourWordButton1)
                .addContainerGap())
        );

        tabs.addTab("tab1", YourWordTab);

        getContentPane().add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -30, 520, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soundButtonActionPerformed(ActionEvent evt) {
        Word w = dictionary.findEngWord(wordLabel.getText());
        if (w == null) {
            return;
        }
        w.playPronunciation(synthesizer);
    }

    private void chooseSearchEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseSearchEnglishActionPerformed
        unSelectAllMenuButtons();
        chooseSearchEnglish.setOpaque(true);
        chooseSearchEnglish.setBorderPainted(true);
        tabs.setSelectedIndex(0);
    }//GEN-LAST:event_chooseSearchEnglishActionPerformed

    private void chooseSearchOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseSearchOnlineActionPerformed
        unSelectAllMenuButtons();
        chooseSearchOnline.setOpaque(true);
        chooseSearchOnline.setBorderPainted(true);
        tabs.setSelectedIndex(2);
    }//GEN-LAST:event_chooseSearchOnlineActionPerformed

    private void searchEngListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchEngListKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_ENTER) {
            return;
        }
        showWord(searchEngList.getSelectedValue());
    }//GEN-LAST:event_searchEngListKeyReleased

    private void searchEngListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEngListMouseReleased
        if (evt.getClickCount() < 2) {
            return;
        }
        var target = (javax.swing.JList<Word>) evt.getSource();
        int index = target.locationToIndex(evt.getPoint());
        if (index >= 0) {
            Word item = target.getModel().getElementAt(index);
            showWord(item);
        }
    }//GEN-LAST:event_searchEngListMouseReleased

    private void FindEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindEngActionPerformed
        Word w = dictionary.findEngWord(inputEngWord.getText());
        if (w == null) {
            return;
        }
        showWord(w);
    }//GEN-LAST:event_FindEngActionPerformed

    private void inputEngWordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputEngWordKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            FindEngActionPerformed(null);
            return;
        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            searchEngList.setListData(new Word[1]);
        }

        var inputText = inputEngWord.getText();

        if (inputText.equals("")) {
            return;
        }
        var words = dictionary.findAllEngWordContain(inputText);
        searchEngList.setListData(words);
    }//GEN-LAST:event_inputEngWordKeyReleased

    private void inputEngWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEngWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEngWordActionPerformed

    private void inputViewWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputViewWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputViewWordActionPerformed

    private void inputViewWordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputViewWordKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            FindEngActionPerformed(null);
            return;
        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            searchVietList.setListData(new Word[1]);
        }

        var inputText = inputViewWord.getText();

        if (inputText.equals("")) {
            return;
        }
        var words = dictionary.findAllVietWordContain(inputText);
        searchVietList.setListData(words);
    }//GEN-LAST:event_inputViewWordKeyReleased

    private void FindVietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindVietActionPerformed
        Word w = dictionary.findVietWord(inputEngWord.getText());
        if (w == null) {
            return;
        }
        showWord(w);
    }//GEN-LAST:event_FindVietActionPerformed

    private void searchVietListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchVietListMouseReleased
        if (evt.getClickCount() < 2) {
            return;
        }
        var target = (javax.swing.JList<Word>) evt.getSource();
        int index = target.locationToIndex(evt.getPoint());
        if (index >= 0) {
            Word item = target.getModel().getElementAt(index);
            showWord(item);
        }
    }//GEN-LAST:event_searchVietListMouseReleased

    private void searchVietListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchVietListKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchVietListKeyReleased

    private void VietEngOnlineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VietEngOnlineButtonActionPerformed
        String inputText = inputOnlineSearchTextArea.getText();
        try {
            String result = translate("en", "vi", inputText);
            outputOnlineSearchTextArea.setText(result);
        } catch (IOException e) {
            outputOnlineSearchTextArea.setText("Cannot translate");
        }
    }//GEN-LAST:event_VietEngOnlineButtonActionPerformed

    private void EngVietOnlineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngVietOnlineButtonActionPerformed
        String inputText = inputOnlineSearchTextArea.getText();
        try {

            String result = translate("vi", "en", inputText);
            outputOnlineSearchTextArea.setText(result);
        } catch (IOException e) {
            outputOnlineSearchTextArea.setText("Cannot translate");
        }
    }//GEN-LAST:event_EngVietOnlineButtonActionPerformed

    public String translate(String langFrom, String langTo, String text) throws IOException {
        String APIKEY = "AKfycbzxtNpZD2Ogs4oeUnj8nTaCmPlKwgwsLWPasyIsLQPB_WXvKdKU";
        URL url = new URL("https://script.google.com/macros/s/" + APIKEY + "/exec?q=" + URLEncoder.encode(text, StandardCharsets.UTF_8) + "&target=" + langTo + "&source=" + langFrom);
        HttpURLConnection request = (HttpURLConnection) url.openConnection();
        request.setRequestProperty("User-Agent", "Mozilla/5.0");
        BufferedReader inputStream = new BufferedReader(new InputStreamReader(request.getInputStream()));
        String inputLine;
        StringBuilder response = new StringBuilder();
        while ((inputLine = inputStream.readLine()) != null) {
            response.append(inputLine);
        }
        inputStream.close();
        return response.toString();
    }

    private void chooseSearchVietnameseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseSearchVietnameseActionPerformed
        unSelectAllMenuButtons();
        chooseSearchVietnamese.setOpaque(true);
        chooseSearchVietnamese.setBorderPainted(true);
        tabs.setSelectedIndex(1);
    }//GEN-LAST:event_chooseSearchVietnameseActionPerformed

    private void chooseYourWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseYourWordsActionPerformed
        unSelectAllMenuButtons();
        chooseYourWords.setOpaque(true);
        chooseYourWords.setBorderPainted(true);
        tabs.setSelectedIndex(4);
    }//GEN-LAST:event_chooseYourWordsActionPerformed

    private void chooseGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseGameActionPerformed

    private void inputYourEngWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputYourEngWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputYourEngWordActionPerformed

    private void inputYourEngWordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputYourEngWordKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            FindEngActionPerformed(null);
            return;
        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            searchYourEngList.setListData(new SimpleDictionary.Word[1]);
        }

        var inputText = inputYourEngWord.getText();

        if (inputText.equals("")) {
            return;
        }
        List<SimpleDictionary.Word> wordsList = simpleDictionary.findAllWordContain(inputText);
        SimpleDictionary.Word[] words = new SimpleDictionary.Word[wordsList.size()];
        wordsList.toArray(words);
        searchYourEngList.setListData(words);
        System.out.println("Input:" + wordsList.size());
    }//GEN-LAST:event_inputYourEngWordKeyReleased

    private void saveChangeYourWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangeYourWordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveChangeYourWordButtonActionPerformed

    private void searchYourEngListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchYourEngListMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchYourEngListMouseReleased

    private void searchYourEngListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchYourEngListKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchYourEngListKeyReleased

    private void showYourVietWordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showYourVietWordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showYourVietWordFieldActionPerformed

    private void showYourVietWordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showYourVietWordFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_showYourVietWordFieldKeyReleased

    private void showYourEngWordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showYourEngWordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showYourEngWordFieldActionPerformed

    private void showYourEngWordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showYourEngWordFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_showYourEngWordFieldKeyReleased

    private void deleteYourWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteYourWordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteYourWordButtonActionPerformed

    private void saveToFileYourWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToFileYourWordButtonActionPerformed
        simpleDictionary.saveToFile();
    }//GEN-LAST:event_saveToFileYourWordButtonActionPerformed

    private void readYourWordFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readYourWordFromFileActionPerformed
        simpleDictionary.insertFromFile();
    }//GEN-LAST:event_readYourWordFromFileActionPerformed

    private void saveChangeYourWordButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangeYourWordButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveChangeYourWordButton1ActionPerformed

    private void addYourEngWordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addYourEngWordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addYourEngWordFieldActionPerformed

    private void addYourEngWordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addYourEngWordFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_addYourEngWordFieldKeyReleased

    private void addYourVietWordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addYourVietWordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addYourVietWordFieldActionPerformed

    private void addYourVietWordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addYourVietWordFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_addYourVietWordFieldKeyReleased

    private void unSelectAllMenuButtons() {
        for (javax.swing.JButton b : menuButtons) {
            b.setOpaque(false);
            b.setBorderPainted(false);
        }
    }

    private void initMenuButton() {
        menuButtons.add(chooseSearchEnglish);
        menuButtons.add(chooseSearchOnline);
        menuButtons.add(chooseSearchVietnamese);
        menuButtons.add(chooseYourWords);
    }

    private void showWord(Word word) {
        tabs.setSelectedIndex(3);
        System.out.println("Show " + word.getPronounce());
        wordLabel.setText(word.getWord());
        pronounce.setText(word.getPronounce());
        wordExplain.setText(word.getDescription() + word.getHtml());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EngVietOnlineButton;
    private javax.swing.JButton FindEng;
    private javax.swing.JButton FindViet;
    private javax.swing.JButton VietEngOnlineButton;
    private javax.swing.JPanel YourWordTab;
    private javax.swing.JTextField addYourEngWordField;
    private javax.swing.JTextField addYourVietWordField;
    private javax.swing.JButton chooseGame;
    private javax.swing.JButton chooseSearchEnglish;
    private javax.swing.JButton chooseSearchOnline;
    private javax.swing.JButton chooseSearchVietnamese;
    private javax.swing.JButton chooseYourWords;
    private javax.swing.JButton deleteYourWordButton;
    private javax.swing.JPanel findEnglishWordTab;
    private javax.swing.JPanel findVietnameseWordTab;
    private javax.swing.JTextField inputEngWord;
    private javax.swing.JTextArea inputOnlineSearchTextArea;
    private javax.swing.JTextField inputViewWord;
    private javax.swing.JTextField inputYourEngWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel nameApp;
    private javax.swing.JLabel nameApp1;
    private javax.swing.JPanel onlineSearchTab;
    private javax.swing.JTextArea outputOnlineSearchTextArea;
    private javax.swing.JLabel pronounce;
    private javax.swing.JButton readYourWordFromFile;
    private javax.swing.JButton saveChangeYourWordButton;
    private javax.swing.JButton saveChangeYourWordButton1;
    private javax.swing.JButton saveToFileYourWordButton;
    private javax.swing.JScrollPane scrollPaneExplain;
    private javax.swing.JList<Word> searchEngList;
    private javax.swing.JList<Word> searchVietList;
    private javax.swing.JList<SimpleDictionary.Word> searchYourEngList;
    private javax.swing.JScrollPane showAllEngSearch;
    private javax.swing.JScrollPane showAllEngSearch1;
    private javax.swing.JScrollPane showAllViewSearch;
    private javax.swing.JTextField showYourEngWordField;
    private javax.swing.JTextField showYourVietWordField;
    private javax.swing.JButton soundButton;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JEditorPane wordExplain;
    private javax.swing.JLabel wordLabel;
    private javax.swing.JPanel wordTab;
    // End of variables declaration//GEN-END:variables
}
