package UI_Dictionary;

import java.awt.event.KeyEvent;

/**
 * @author Quan
 */
public class MainFrame extends javax.swing.JFrame {

    private FindEnglishWord findEnglishWordFrame;
    private FindVietWord findVietWordFrame;
    private OnlineSearch onlineSearchFrame;
    private Game game;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        findEnglishWordFrame = new FindEnglishWord();
        findEnglishWordFrame.setMainFrame(this);
        findVietWordFrame = new FindVietWord();
        findVietWordFrame.setMainFrame(this);
        onlineSearchFrame = new OnlineSearch();
        onlineSearchFrame.setMainFrame(this);
        game = new Game();
        game.setMainFrame(this);
        initComponents();
    }

    public void setFindEnglishWordFrame(FindEnglishWord findEnglishWordFrame) {
        this.findEnglishWordFrame = findEnglishWordFrame;
    }

    public FindEnglishWord getFindEnglishWordFrame() {
        return findEnglishWordFrame;
    }

    public void setFindVietWordFrame(FindVietWord findVietWordFrame) {
        this.findVietWordFrame = findVietWordFrame;
    }

    public FindVietWord getFindVietWordFrame() {
        return findVietWordFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        openSearchEngWord = new javax.swing.JButton();
        openSearchVietWord = new javax.swing.JButton();
        openGame = new javax.swing.JButton();
        openOnlineSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        Name.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("TỪ ĐIỂN TIẾNG ANH");

        openSearchEngWord.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        openSearchEngWord.setText("Tra tiếng Anh");
        openSearchEngWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSearchEngWordActionPerformed(evt);
            }
        });

        openSearchVietWord.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        openSearchVietWord.setText("Tra tiếng Việt");
        openSearchVietWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSearchVietWordActionPerformed(evt);
            }
        });

        openGame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        openGame.setText("Trò chơi");
        openGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openGameActionPerformed(evt);
            }
        });

        openOnlineSearch.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        openOnlineSearch.setText("Dịch Online");
        openOnlineSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openOnlineSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openSearchEngWord, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                            .addComponent(openSearchVietWord, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                            .addComponent(openGame, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                            .addComponent(openOnlineSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
                        .addGap(101, 101, 101))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
         
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openSearchEngWord, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(openSearchVietWord, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(openOnlineSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(openGame, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openSearchEngWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSearchEngWordActionPerformed
        findEnglishWordFrame.setVisible(true);
        findEnglishWordFrame.setLocation(this.getLocation());
        this.setVisible(false);
    }//GEN-LAST:event_openSearchEngWordActionPerformed

    private void openSearchVietWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSearchVietWordActionPerformed
        findVietWordFrame.setVisible(true);
        findVietWordFrame.setLocation(this.getLocation());
        this.setVisible(false);
    }//GEN-LAST:event_openSearchVietWordActionPerformed

    private void openGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openGameActionPerformed

    }//GEN-LAST:event_openGameActionPerformed

    private void openOnlineSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openOnlineSearchActionPerformed
        onlineSearchFrame.setVisible(true);
        onlineSearchFrame.setLocation(this.getLocation());
        this.setVisible(false);
    }//GEN-LAST:event_openOnlineSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public void Init() {
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JButton openGame;
    private javax.swing.JButton openOnlineSearch;
    private javax.swing.JButton openSearchEngWord;
    private javax.swing.JButton openSearchVietWord;
    // End of variables declaration//GEN-END:variables
}
